import mongoose from "mongoose";

const finalDetails=new mongoose.Schema({
  user:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Faculty",
    required:true
  },
  foreign_visits: {type:Array,default:[]},
  patents:{type:Array,default:[]},  
  awards_and_recognitions:{type:Array,default:[]},  
  book_chapter: {type:Array,default:[]},
  book: {type:Array,default:[]},
  journal:{type:Array,default:[]},
  conference_paper:{type:Array,default:[]},
  nptel:{type:Array,default:[]},
  swayam: {type:Array,default:[]},
  coursera: {type:Array,default:[]},
  infosysspringboard:{type:Array,default:[]},
  edx: {type:Array,default:[]},
  other:{type:Array,default:[]},
  sponsored: {type:Array,default:[]},
  research:{type:Array,default:[]},
  consultancy:{type:Array,default:[]},
  fdp: {type:Array,default:[]},
  sttp:{type:Array,default:[]},
  conference: {type:Array,default:[]},
  workshop: {type:Array,default:[]},
  seminar: {type:Array,default:[]},
  webinar: {type:Array,default:[]},
  rc: {type:Array,default:[]},
  oc:{type:Array,default:[]},
  talk: {type:Array,default:[]},
  keynote: {type:Array,default:[]},
  chair:{type:Array,default:[]},
  committee:{type:Array,default:[]},
  lecture:{type:Array,default:[]},
  resource_person: {type:Array,default:[]},
  mooc_content: {type:Array,default:[]},
  e_content:{type:Array,default:[]},
  innovative_pedagogy:{type:Array,default:[]},
  award_title: {type:Array,default:[]},
  ieee:{type:Array,default:[]},
  acm:{type:Array,default:[]},
  csi: {type:Array,default:[]},
  ie:{type:Array,default:[]},
  iete:{type:Array,default:[]},
  other_bodies:{type:Array,default:[]},
  any_moocs_course: {type:Array,default:[]},
  book_book_chapter:{type:Array,default:[]},
  phd_awarded:{type:Array,default:[]},
  phd_ongoing: {type:Array,default:[]},
  mtech:{type:Array,default:[]}
})

export default mongoose.model("Credentials",finalDetails)